### ISSUE TITLE
No Config.yml

### ISSUE THREAD

**Issue by fredghostkyle** [TVPT/VoxelGunsmith#6]
Hi, This is something on Cauldron's side so don't worry about it but I can't find your config.yml. Can I have a copy of it? Thanks, FRED.

**Comment by Deamon5550** [comment]
Not too sure about the setup for cauldron, I've never tested VoxelSniper on it before, but in the same directory as the VoxelSniper jar there should be a folder named 'VoxelSniper' and inside of there is a number of configuration files (as well as some data files).

**Comment by fredghostkyle** [comment]
No, that thing is that those files don't create, that's the issue. I just need some that are already pre-generated.

**Comment by fredghostkyle** [comment]
@Deamon5550 Just so you know, this happens on all plugins except WorldGuard and WorldEdit. So I'm not surprised by it.

**Comment by Deamon5550** [comment]
What version is this for? Any build based on VoxelGunsmith is only supported for minecraft 1.8 and higher. For older versions the last supported version is [http://files.thevoxelbox.com/Plugins/VoxelSniper/VoxelSniper-5.170.0.jar](http://files.thevoxelbox.com/Plugins/VoxelSniper/VoxelSniper-5.170.0.jar)

**Comment by fredghostkyle** [comment]
@Deamon5550 I don't have permission for that link. 
It's for a 1.7.9 server, I can get you the exact jar I'm using.

**Comment by Deamon5550** [comment]
Ah derp I've fixed the permissions on that file. And yeah if its 1.7.9 then its unsupported by the more recent versions, although the old one should still work, and if its missing config...well it had almost none anyway.
